### ISSUE TITLE
Need to be able to edit/see objects tagged using closed ways

### ISSUE THREAD

**Issue by zhm** [pushpin/pushpinosm.org#5]
There are a lot of "POIs" in OSM that are closed ways tagged with the information about the place. The user should be able to view and edit the object's tags from the app to prevent duplicate data being entered.

**Comment by harry-wood** [comment]
This is a significant problem.  Easy mistake to make :-)  https://twitter.com/mapnik/statuses/255329260674375680

Tip for users would be to check on the map view (as opposed to just aerial imagery) before adding stuff, but even then you're not guaranteed to get a pub icon because of rendering collisions.

It could be there's a good way to solve this server-side. I thought for a long time that OpenStreetMap should offer a POI only planet download and read-only API which would give a condensed representation of just the centroid for POIs as areas.

**Comment by zhm** [comment]
I've been hacking on this over the last two nights, and now the app can view closed ways and even multipolygon relations. I still need to finish up the editing of tags of these features also. The geometry of ways and relations will not be editable, so there's no danger of breaking geometries or the members of relations.

Below is a screenshot of how it's presented in the app:

![relation](http://cl.ly/image/1s1G1N320J2d/Screen%20Shot%202012-10-23%20at%201.07.56%20PM.png)

**Comment by harry-wood** [comment]
nice!

**Comment by zhm** [comment]
This is available now in 1.1 :)
